### ISSUE TITLE
adjust max and min curves at the same time

### ISSUE THREAD

**Issue by madeinspace** [westlicht/performer#103]
It would be nice to adjust the curve offset for both min and max value at the same time to keep the range unmodified. thanks for considering! :)

**Comment by westlicht** [comment]
Do you have a specific idea of how this would be accessible? SHIFT is already used for fine adjustment.

**Comment by soporus** [comment]
Maybe an offset mode added to F4?

**Comment by westlicht** [comment]
@soporus I consider that a break from the current design because the function buttons are used to select layers. Each layer represents a piece of per-step data and is represented exactly once. Adding an offset button would imply there is another layer, but that is not the case as it would change the existing min/max layers. In addition, these additional function buttons will probably be used in the near future for other layers that I'm considering to add to curve sequences. So I'm afraid I'm not too fond of that idea.

**Comment by westlicht** [comment]
Just to be clear, I think there would be some value in being able to "offset" curve segments, I'm just not sure what the best way of achieving this could look like.

**Comment by madeinspace** [comment]
@westlicht I'll have a think, maybe by holding max and min while turning the encoder?

**Comment by westlicht** [comment]
> maybe by holding max and min while turning the encoder?

had the same thought, but it also doesn't fit too well with the existing UI

**Comment by westlicht** [comment]
I've just implemented a version where you can keep holding min or max (not and) function keys to offset the curve segment. I'm not sure I like this yet, but it's an option.

**Comment by westlicht** [comment]
Will be part of the 0.1.27 release.
