### ISSUE TITLE
Feature Request: undo 

### ISSUE THREAD

**Issue by JnsVttr** [westlicht/performer#235]
I love the Performer! A very handy feature would be an 'undo' option. Sometimes I just delete accidentally some notes/ curves  and an 'undo' would help a lot in reverting to the previous states without re-loading the entire project.
greets.

**Comment by westlicht** [comment]
Implementing a good undo/redo function is tricky due to memory constraints. For that reason (and others) I implemented the _snapshot_ feature early on. On the pattern page you can hit the `SNAP` function to make a copy of the currently playing patterns. This can be done on the fly while the sequencer is running. While the snapshot is active (shown at the top of the display) you can do edits in the sequences as before. You then have the option to `COMMIT` or `REVERT` to leave snapshot mode where the first copies the snapshot back to the original patterns (or optionally to a different one) and the second discards all edits. You can use this feature instead of undo. Just enter snapshot mode before doing edits. If you're happy, commit the changes, otherwise revert. It's a bit of a different workflow but it's the best alternative to undo you can get on performer.
