### ISSUE TITLE
Buttons inactive after boot (issue 248 cont)

### ISSUE THREAD

**Issue by papastratman** [westlicht/performer#283]
Hey there,
I submitted an issue on this before (# 248) and thought it was resolved, but alas it was not resolved, it was being an intermittent issue. 
When I powered up one of my Performers (after using it without issue for approx 4 months), the buttons were unresponsive and the button LEDs didn't cycle as per usual on boot. Since then it will occasionally work fine however it will sometimes be unresponsive at boot and it will sometimes start cycling through menus and tracks without any input after being on and working correctly for a few minutes. 
The encoder dial works fine, the screen works fine, the buttons do not. 
The suggested solution to issue # 248 was to check the shift registers for a cold solder joint. I have done so, and not found any. I re-flowed the solder on all the shift registers just to make sure. The issue persists. 
Could a shift register be failing completely and cause this? Any other thoughts?
Thank you very much for the help.

**Comment by westlicht** [comment]
Are you using the recommended leds? The current sinking shift register can take damage if you draw too much current. In any case, this problem is definitely a hardware issue. I would suggest to just replace the shift registers. They are very cheap and you probably will have a working unit again. Closing this as it's not firmware related.
