### ISSUE TITLE
Banks for more than 16 pattern

### ISSUE THREAD

**Issue by xhsi** [westlicht/performer#46]
Banks for pattern would be nice.
16 pattern per project seem a little less.

**Comment by westlicht** [comment]
Unfortunately this is not possible due to memory limitations. All data is kept in RAM for immediate access which is very limited with 192k. This could only be changed with a new hardware design that has integrates an external RAM chip. But that would be a full redesign as it would also require the STM32 on a larger package (for all the bus pins) and would make the module harder to DIY.
