### ISSUE TITLE
New routing targets

### ISSUE THREAD

**Issue by westlicht** [westlicht/performer#89]
Add new routing targets:
- track mute
- track fill
- track fill amount
- pattern

**Comment by westlicht** [comment]
Fixes #51, #65 and #71.

**Comment by sneak-thief** [comment]
If what I'm envisioning is at all possible, I'm very curious to test some recursive muting scenarios with several tracks un/muting one another. This is Cirklon territory :D

**Comment by westlicht** [comment]
> If what I'm envisioning is at all possible, I'm very curious to test some recursive muting scenarios with several tracks un/muting one another. This is Cirklon territory :D

Haha, sure, why not :D

**Comment by westlicht** [comment]
To be released with 0.1.22.

**Comment by dijfsanders** [comment]
The Pattern change over midi seems to be buggy. If i use more than one pattern routing, it doesn't respond anymore. It seems to react badly on Note numbers instead of CC. Only if i route pattern [1-16] to a CC, it respond correctly. (i use a AKAI APCKey25)

**Comment by westlicht** [comment]
> The Pattern change over midi seems to be buggy. If i use more than one pattern routing, it doesn't respond anymore. It seems to react badly on Note numbers instead of CC. Only if i route pattern [1-16] to a CC, it respond correctly. (i use a AKAI APCKey25)

That's expected behaviour. The implementation does not allow to have multiple routes targeting the same target parameter. Only if you target different tracks, you can have multiple routes going to the "same" target (but on different tracks). I think there are two things that could improve this:

1. Do not allow setting up conflicting routes in the first place.
2. Add a new "note range" source, that routes a range of MIDI note values to some target value. E.g. you could setup MIDI notes C3-D#4 as a range to control the pattern number.

**Comment by dijfsanders** [comment]
Thanks for the feedback!
So, this 'Note Range' is something you will implement in a next update?

greets
D

________________________________
Van: Simon Kallweit <notifications@github.com>
Verzonden: zondag 7 juli 2019 22:03
Aan: westlicht/performer
CC: dijfsanders; Comment
Onderwerp: Re: [westlicht/performer] New routing targets (#89)


The Pattern change over midi seems to be buggy. If i use more than one pattern routing, it doesn't respond anymore. It seems to react badly on Note numbers instead of CC. Only if i route pattern [1-16] to a CC, it respond correctly. (i use a AKAI APCKey25)

That's expected behaviour. The implementation does not allow to have multiple routes targeting the same target parameter. Only if you target different tracks, you can have multiple routes going to the "same" target (but on different tracks). I think there are two things that could improve this:

  1.  Do not allow setting up conflicting routes in the first place.
  2.  Add a new "note range" source, that routes a range of MIDI note values to some target value. E.g. you could setup MIDI notes C3-D#4 as a range to control the pattern number.

**Comment by westlicht** [comment]
Yes, prototype to address both points is already working.
